[build]
  command = "# no build command"
  publish = "public"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/"
  to = "/.netlify/functions/barcode"
  status = 200
  force = true
